"""[R12-9 BSG-VA] Auto-generated seed-mode characterization replay test.

Generated by scp.autofix.evidence_replay.prepare_seed_replay for a
first-time bug signature (gold-seeding policy). Pins the OBSERVED
behavior of the candidate (fixed) module so the BSG replay can
discriminate the buggy state from the fixed state with a real pytest
subprocess run (DNA #26). Throwaway artifact: exists only inside the
replay temp workspace.
"""
import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import cand_mod


def test_replay_f() -> None:
    """Pin observed candidate behavior of cand_mod.f."""
    assert repr(cand_mod.f()) == "{'echo', 'delta', 'alpha', 'bravo', 'charlie'}"

