"""Exact-SHA release evidence binding for SCP.

Evidence generated by this module is bound to an immutable git commit plus
hashes of the SCP DNA, Skill manifests, test profile, configuration and release
manifest surfaces that exist at that commit. Validation is fail-closed: stale
SHA, tampering, malformed evidence or an unverifiable repository snapshot all
return ``False``.
"""
from __future__ import annotations

import hashlib
import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import logging

from scp.core.safe_process import safe_run
logger = logging.getLogger(__name__)



_SCHEMA_VERSION = "scp-evidence-authority-v1"
_FULL_SHA_RE = re.compile(r"^[0-9a-f]{40}$")

_DNA_PATHS = (
    ".agents/skills/scp-dna/SKILL.md",
    ".agents/skills/scp-dna/references/dna-principles.md",
)
_TEST_PROFILE_PATHS = (
    ".github/workflows/ci.yml",
    ".github/workflows/scp-release-gate.yml",
    ".github/workflows/scp-rc-promotion.yml",
    "scripts/enforce_baseline.py",
    "scripts/run_system_audit_strict.py",
)
_CONFIG_PATHS = (
    "spec/complete_scp_reference.yaml",
    "spec/implementation_bindings.yaml",
)
_MANIFEST_PATHS = (
    ".agents/skills/release-gate-skill-dna-bindings.json",
)


def _canonical_json(value: Any) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


class EvidenceAuthority:
    """Generate and validate immutable, exact-SHA SCP release evidence."""

    def __init__(self, repo_path: str | Path) -> None:
        self.repo_path = Path(repo_path).resolve()
        self._git("rev-parse", "--git-dir")

    def _git(self, *args: str, text: bool = True) -> str | bytes:
        completed = safe_run(
            ["git", "-C", str(self.repo_path), *args],
            check=True,
            capture_output=True,
            text=text,
        )
        if text:
            return completed.stdout.strip()
        return completed.stdout

    def _resolve_commit(self, ref: str) -> str:
        resolved = str(self._git("rev-parse", "--verify", f"{ref}^{{commit}}"))
        if not _FULL_SHA_RE.fullmatch(resolved):
            raise ValueError(f"git ref did not resolve to a full commit SHA: {ref!r}")
        return resolved

    def _tree_paths(self, tested_sha: str) -> set[str]:
        output = str(self._git("ls-tree", "-r", "--name-only", tested_sha))
        return {line.strip() for line in output.splitlines() if line.strip()}

    def _blob_hash(self, tested_sha: str, path: str, available: set[str]) -> str:
        if path not in available:
            return "MISSING"
        data = self._git("show", f"{tested_sha}:{path}", text=False)
        assert isinstance(data, bytes)
        return _sha256(data)

    def _hash_paths(
        self,
        tested_sha: str,
        paths: Iterable[str],
        available: set[str],
    ) -> dict[str, str]:
        return {
            path: self._blob_hash(tested_sha, path, available)
            for path in sorted(set(paths))
        }

    def _artifact_hashes(self, tested_sha: str) -> dict[str, Any]:
        available = self._tree_paths(tested_sha)
        skill_paths = sorted(
            path
            for path in available
            if path.startswith(".agents/skills/scp-") and path.endswith("/SKILL.md")
        )
        tree_listing = str(self._git("ls-tree", "-r", tested_sha)).encode("utf-8")
        return {
            "repository_tree_sha256": _sha256(tree_listing),
            "dna": self._hash_paths(tested_sha, _DNA_PATHS, available),
            "skills": self._hash_paths(tested_sha, skill_paths, available),
            "test_profile": self._hash_paths(tested_sha, _TEST_PROFILE_PATHS, available),
            "config": self._hash_paths(tested_sha, _CONFIG_PATHS, available),
            "manifest": self._hash_paths(tested_sha, _MANIFEST_PATHS, available),
        }

    def generate_evidence(
        self,
        output: str | Path,
        tested_sha: str,
        *,
        metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Write evidence bound to ``tested_sha`` and return the payload.

        ``tested_sha`` must be a full 40-character commit SHA. It is deliberately
        allowed to differ from current HEAD so a completed test run can be bound
        to the commit it actually exercised. Validation decides whether that
        evidence is current or stale for a requested head.
        """
        resolved = self._resolve_commit(tested_sha)
        if tested_sha != resolved:
            raise ValueError("tested_sha must be the exact full commit SHA")

        artifact_hashes = self._artifact_hashes(resolved)
        snapshot_digest = _sha256(_canonical_json(artifact_hashes))
        core: dict[str, Any] = {
            "schema_version": _SCHEMA_VERSION,
            "tested_sha": resolved,
            "generated_at_utc": datetime.now(timezone.utc).isoformat(),
            "artifact_hashes": artifact_hashes,
            "snapshot_digest": snapshot_digest,
            "metadata": dict(metadata or {}),
        }
        payload = dict(core)
        payload["evidence_digest"] = _sha256(_canonical_json(core))

        output_path = Path(output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(
            json.dumps(payload, sort_keys=True, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        return payload

    def validate_evidence(
        self,
        evidence_path: str | Path,
        *,
        current_head: str | None = None,
    ) -> bool:
        """Return ``True`` only for intact evidence bound to the current SHA."""
        try:
            payload = json.loads(Path(evidence_path).read_text(encoding="utf-8"))
            if not isinstance(payload, dict):
                return False
            if payload.get("schema_version") != _SCHEMA_VERSION:
                return False

            tested_sha = payload.get("tested_sha")
            if not isinstance(tested_sha, str) or not _FULL_SHA_RE.fullmatch(tested_sha):
                return False
            if self._resolve_commit(tested_sha) != tested_sha:
                return False

            requested_head = current_head if current_head is not None else "HEAD"
            resolved_head = self._resolve_commit(requested_head)
            if resolved_head != tested_sha:
                return False

            evidence_digest = payload.get("evidence_digest")
            if not isinstance(evidence_digest, str):
                return False
            core = dict(payload)
            core.pop("evidence_digest", None)
            if _sha256(_canonical_json(core)) != evidence_digest:
                return False

            artifact_hashes = payload.get("artifact_hashes")
            if not isinstance(artifact_hashes, dict):
                return False
            if self._artifact_hashes(tested_sha) != artifact_hashes:
                return False
            if _sha256(_canonical_json(artifact_hashes)) != payload.get("snapshot_digest"):
                return False
            return True
        except (OSError, ValueError, TypeError, json.JSONDecodeError, subprocess.SubprocessError):
            logger.debug('EvidenceAuthority.validate_evidence: OSError, ValueError, TypeError, json.JSONDecodeError, subprocess.SubprocessError ignored', exc_info=True)
            return False


class ReleaseEvidenceAuthority(EvidenceAuthority):
    """Release evidence authority compatibility wrapper for /v100/release/evidence."""

    def __init__(self, db_path: Path | str | None = None, repo_path: str | Path = ".") -> None:
        try:
            super().__init__(repo_path)
        except Exception:
            self.repo_path = Path(repo_path).resolve()
        self.db_path = Path(db_path) if db_path else None

    def generate_release_claim(self, tested_sha: str | None = None) -> dict[str, Any]:
        """Generate release claim bound to repository commit snapshot."""
        try:
            sha = tested_sha or str(self._resolve_commit("HEAD"))
            artifact_hashes = self._artifact_hashes(sha)
            snapshot_digest = _sha256(_canonical_json(artifact_hashes))
            core: dict[str, Any] = {
                "schema_version": _SCHEMA_VERSION,
                "tested_sha": sha,
                "generated_at_utc": datetime.now(timezone.utc).isoformat(),
                "artifact_hashes": artifact_hashes,
                "snapshot_digest": snapshot_digest,
            }
            core["evidence_digest"] = _sha256(_canonical_json(core))
            return core
        except Exception as exc:
            return {
                "schema_version": _SCHEMA_VERSION,
                "status": "UNAVAILABLE",
                "error": str(exc),
            }

